// Three-level taxonomy: field → subfield → sub-subfields
// All hardcoded for instant sidebar navigation with no API calls
export const ACADEMIC_TAXONOMY = {
  'Mathematics': {
    'Algebra': ['Group Theory', 'Ring Theory', 'Linear Algebra', 'Commutative Algebra', 'Homological Algebra', 'Representation Theory', 'Galois Theory'],
    'Analysis': ['Real Analysis', 'Complex Analysis', 'Functional Analysis', 'Harmonic Analysis', 'Measure Theory', 'Calculus of Variations'],
    'Topology': ['Algebraic Topology', 'Differential Topology', 'General Topology', 'Geometric Topology', 'Knot Theory'],
    'Geometry': ['Differential Geometry', 'Algebraic Geometry', 'Riemannian Geometry', 'Symplectic Geometry', 'Discrete Geometry'],
    'Number Theory': ['Analytic Number Theory', 'Algebraic Number Theory', 'Arithmetic Geometry', 'Combinatorial Number Theory', 'Modular Forms'],
    'Combinatorics': ['Graph Theory', 'Enumerative Combinatorics', 'Extremal Combinatorics', 'Probabilistic Combinatorics', 'Matroid Theory'],
    'Logic & Foundations': ['Mathematical Logic', 'Set Theory', 'Model Theory', 'Proof Theory', 'Category Theory', 'Computability Theory'],
    'Probability Theory': ['Stochastic Calculus', 'Martingale Theory', 'Large Deviations', 'Random Graphs', 'Stochastic Processes'],
    'Differential Equations': ['Ordinary Differential Equations', 'Partial Differential Equations', 'Dynamical Systems', 'Chaos Theory'],
    'Numerical Analysis': ['Numerical Linear Algebra', 'Finite Element Methods', 'Numerical Optimization', 'Approximation Theory'],
  },
  'Statistics & Probability': {
    'Bayesian Statistics': ['Bayesian Inference', 'Bayesian Computation', 'Bayesian Nonparametrics', 'Hierarchical Models'],
    'Statistical Learning': ['Supervised Learning', 'Unsupervised Learning', 'Statistical Decision Theory', 'High-Dimensional Statistics'],
    'Stochastic Processes': ['Markov Chains', 'Brownian Motion', 'Point Processes', 'Random Fields'],
    'Time Series Analysis': ['ARIMA Models', 'State Space Models', 'Spectral Analysis', 'Forecasting'],
    'Causal Inference': ['Potential Outcomes Framework', 'Structural Causal Models', 'Instrumental Variables', 'Regression Discontinuity'],
    'Experimental Design': ['Randomized Controlled Trials', 'Factorial Designs', 'Adaptive Designs', 'A/B Testing'],
    'Multivariate Analysis': ['Principal Component Analysis', 'Factor Analysis', 'Cluster Analysis', 'Discriminant Analysis'],
    'Nonparametric Statistics': ['Rank Tests', 'Kernel Methods', 'Bootstrap Methods', 'Permutation Tests'],
    'Biostatistics': ['Survival Analysis', 'Clinical Trials', 'Longitudinal Data Analysis', 'Epidemiological Methods', 'Genomic Data Analysis'],
    'Spatial Statistics': ['Geostatistics', 'Spatial Regression', 'Point Pattern Analysis', 'Kriging', 'Spatial Econometrics'],
    'Robust Statistics': ['Influence Functions', 'M-Estimators', 'Outlier Detection', 'Robust Regression'],
  },
  'Physics': {
    'Classical Mechanics': ['Lagrangian Mechanics', 'Hamiltonian Mechanics', 'Celestial Mechanics', 'Fluid Dynamics', 'Chaos & Nonlinear Dynamics'],
    'Quantum Mechanics': ['Quantum Information', 'Quantum Computing', 'Scattering Theory', 'Many-Body Quantum Mechanics', 'Quantum Optics'],
    'Statistical Mechanics': ['Thermodynamics', 'Phase Transitions', 'Kinetic Theory', 'Non-equilibrium Statistical Mechanics'],
    'Electromagnetism': ['Classical Electrodynamics', 'Plasma Physics', 'Magnetohydrodynamics', 'Photonics'],
    'Quantum Field Theory': ['Gauge Theory', 'Renormalization', 'Conformal Field Theory', 'Topological Field Theory', 'String Theory'],
    'General Relativity': ['Black Hole Physics', 'Cosmology', 'Gravitational Waves', 'Quantum Gravity'],
    'Condensed Matter Physics': ['Solid State Physics', 'Superconductivity', 'Topological Phases', 'Strongly Correlated Systems'],
    'Particle Physics': ['Standard Model', 'Beyond the Standard Model', 'Collider Physics', 'Neutrino Physics'],
    'Astrophysics & Cosmology': ['Stellar Physics', 'Galactic Dynamics', 'Observational Cosmology', 'High-Energy Astrophysics'],
    'Optics': ['Nonlinear Optics', 'Laser Physics', 'Fiber Optics', 'Quantum Optics'],
    'Atomic, Molecular & Optical Physics': ['Ultracold Atoms', 'Laser Cooling & Trapping', 'Spectroscopy', 'Quantum Control', 'Molecular Physics'],
    'Biophysics': ['Biological Membranes', 'Single-Molecule Biophysics', 'Neurophysics', 'Soft Matter', 'Protein Dynamics'],
  },
  'Chemistry': {
    'Organic Chemistry': ['Reaction Mechanisms', 'Synthetic Organic Chemistry', 'Stereochemistry', 'Natural Products Chemistry', 'Organocatalysis'],
    'Inorganic Chemistry': ['Coordination Chemistry', 'Organometallic Chemistry', 'Solid-State Chemistry', 'Bioinorganic Chemistry'],
    'Physical Chemistry': ['Quantum Chemistry', 'Chemical Thermodynamics', 'Chemical Kinetics', 'Spectroscopy', 'Surface Chemistry'],
    'Analytical Chemistry': ['Chromatography', 'Mass Spectrometry', 'Electroanalytical Chemistry', 'Spectroanalytical Methods'],
    'Biochemistry': ['Protein Biochemistry', 'Enzyme Kinetics', 'Metabolic Biochemistry', 'Nucleic Acid Biochemistry'],
    'Computational Chemistry': ['Density Functional Theory', 'Molecular Dynamics', 'Monte Carlo Methods', 'Cheminformatics'],
    'Materials Chemistry': ['Polymers', 'Nanomaterials', 'Electronic Materials', 'Biomaterials'],
    'Electrochemistry': ['Electrocatalysis', 'Electrochemical Energy Storage', 'Corrosion', 'Photoelectrochemistry'],
  },
  'Biology': {
    'Cell Biology': ['Cell Signaling', 'Cytoskeleton', 'Membrane Biology', 'Cell Division', 'Organelle Biology'],
    'Molecular Biology': ['Gene Expression', 'Epigenetics', 'RNA Biology', 'DNA Replication & Repair', 'Proteomics'],
    'Genetics': ['Classical Genetics', 'Population Genetics', 'Genomics', 'Quantitative Genetics', 'Genetic Engineering'],
    'Evolutionary Biology': ['Natural Selection', 'Phylogenetics', 'Speciation', 'Evolutionary Ecology', 'Evo-Devo'],
    'Ecology': ['Population Ecology', 'Community Ecology', 'Ecosystem Ecology', 'Conservation Biology', 'Behavioral Ecology'],
    'Developmental Biology': ['Embryology', 'Stem Cell Biology', 'Pattern Formation', 'Regeneration'],
    'Microbiology': ['Bacteriology', 'Virology', 'Mycology', 'Microbial Ecology', 'Microbial Genetics'],
    'Immunology': ['Innate Immunity', 'Adaptive Immunity', 'Immunopathology', 'Vaccinology', 'Tumor Immunology'],
    'Systems Biology': ['Gene Regulatory Networks', 'Metabolic Networks', 'Synthetic Biology', 'Bioinformatics'],
    'Structural Biology': ['X-ray Crystallography', 'Cryo-EM', 'NMR Spectroscopy', 'Protein Folding'],
    'Plant Biology & Botany': ['Plant Physiology', 'Plant Development', 'Plant Ecology', 'Plant Genetics', 'Plant-Microbe Interactions'],
    'Marine Biology & Zoology': ['Marine Ecology', 'Animal Behavior', 'Comparative Physiology', 'Invertebrate Biology', 'Vertebrate Biology'],
    'Biotechnology': ['Recombinant DNA Technology', 'CRISPR & Gene Editing', 'Industrial Biotechnology', 'Bioprocessing', 'Agricultural Biotechnology'],
  },
  'Neuroscience': {
    'Cognitive Neuroscience': ['Memory & Learning', 'Attention', 'Decision Making', 'Language & Brain', 'Consciousness'],
    'Computational Neuroscience': ['Neural Coding', 'Network Models', 'Theoretical Neuroscience', 'Connectomics'],
    'Molecular & Cellular Neuroscience': ['Synaptic Transmission', 'Ion Channels', 'Neuroplasticity', 'Glial Biology', 'Neurotransmitters'],
    'Systems Neuroscience': ['Sensory Systems', 'Motor Systems', 'Basal Ganglia', 'Hippocampus & Memory', 'Prefrontal Cortex'],
    'Behavioral Neuroscience': ['Learning & Memory', 'Motivation & Reward', 'Sleep & Circadian Rhythms', 'Stress & Emotion'],
    'Clinical Neuroscience': ['Neurodegenerative Diseases', 'Epilepsy', 'Psychiatric Disorders', 'Neurorehabilitation'],
    'Developmental Neuroscience': ['Neurogenesis', 'Axon Guidance', 'Synaptogenesis', 'Critical Periods', 'Neurodevelopmental Disorders'],
    'Neuroimaging': ['fMRI Methods', 'EEG & MEG', 'Diffusion Tensor Imaging', 'Multimodal Neuroimaging', 'Connectome Mapping'],
  },
  'Computer Science': {
    'Algorithms & Data Structures': ['Sorting & Searching', 'Graph Algorithms', 'Dynamic Programming', 'Approximation Algorithms', 'Randomized Algorithms'],
    'Theory of Computation': ['Computability Theory', 'Complexity Theory', 'Automata Theory', 'Information Theory'],
    'Operating Systems': ['Process Management', 'Memory Management', 'File Systems', 'Concurrency'],
    'Computer Architecture': ['Processor Design', 'Memory Hierarchy', 'Parallel Architecture', 'GPU Architecture'],
    'Databases': ['Relational Databases', 'NoSQL Databases', 'Query Optimization', 'Distributed Databases', 'Data Warehousing'],
    'Computer Networks': ['Network Protocols', 'Internet Architecture', 'Wireless Networks', 'Network Security'],
    'Programming Languages': ['Type Theory', 'Compilers', 'Functional Programming', 'Program Analysis', 'Formal Verification'],
    'Software Engineering': ['Software Design Patterns', 'Testing & Verification', 'Agile Methods', 'Software Architecture'],
    'Computer Graphics': ['Rendering', 'Geometry Processing', 'Animation', 'Visualization'],
    'Distributed Systems': ['Consensus Algorithms', 'Fault Tolerance', 'Distributed Storage', 'Cloud Computing'],
    'Cryptography': ['Public-Key Cryptography', 'Symmetric Cryptography', 'Zero-Knowledge Proofs', 'Post-Quantum Cryptography'],
    'Cybersecurity': ['Network Security', 'Malware Analysis', 'Vulnerability Research', 'Security Protocols', 'Privacy & Data Security'],
    'Bioinformatics & Computational Biology': ['Sequence Analysis', 'Structural Bioinformatics', 'Phylogenetics', 'Systems Bioinformatics', 'Genomic Data Science'],
    'Human-Computer Interaction': ['Usability Engineering', 'Interaction Design', 'Accessibility', 'Computer-Supported Cooperative Work', 'User Experience'],
  },
  'Artificial Intelligence': {
    'Machine Learning': ['Supervised Learning', 'Unsupervised Learning', 'Semi-Supervised Learning', 'Ensemble Methods', 'Kernel Methods'],
    'Deep Learning': ['Convolutional Neural Networks', 'Recurrent Neural Networks', 'Transformers', 'Generative Adversarial Networks', 'Diffusion Models'],
    'Natural Language Processing': ['Language Models', 'Machine Translation', 'Information Extraction', 'Sentiment Analysis', 'Question Answering'],
    'Computer Vision': ['Object Detection', 'Image Segmentation', 'Visual Recognition', '3D Vision', 'Video Understanding'],
    'Reinforcement Learning': ['Model-Free RL', 'Model-Based RL', 'Multi-Agent RL', 'Reward Shaping', 'Hierarchical RL'],
    'Knowledge Representation': ['Ontologies', 'Knowledge Graphs', 'Logical Reasoning', 'Probabilistic Graphical Models'],
    'Robotics': ['Motion Planning', 'Robot Perception', 'Manipulation', 'Human-Robot Interaction', 'SLAM'],
    'AI Ethics & Safety': ['Fairness & Bias', 'Interpretability', 'AI Alignment', 'Privacy in ML', 'Robustness'],
    'Generative Models': ['Variational Autoencoders', 'Flow Models', 'Energy-Based Models', 'Foundation Models'],
  },
  'Economics': {
    'Microeconomics': ['Consumer Theory', 'Producer Theory', 'General Equilibrium', 'Information Economics', 'Contract Theory'],
    'Macroeconomics': ['Business Cycles', 'Monetary Economics', 'Fiscal Policy', 'Economic Growth', 'Open Economy Macroeconomics'],
    'Econometrics': ['Linear Models', 'Time Series Econometrics', 'Panel Data', 'Structural Estimation', 'Treatment Effects'],
    'Game Theory': ['Non-Cooperative Game Theory', 'Cooperative Game Theory', 'Mechanism Design', 'Evolutionary Game Theory'],
    'Behavioral Economics': ['Bounded Rationality', 'Prospect Theory', 'Social Preferences', 'Nudge Theory'],
    'Labor Economics': ['Human Capital', 'Labor Markets', 'Wage Determination', 'Labor Discrimination', 'Immigration'],
    'Industrial Organization': ['Market Structure', 'Antitrust Economics', 'Regulation', 'Platform Economics'],
    'International Economics': ['International Trade', 'Trade Policy', 'International Finance', 'Exchange Rates'],
    'Development Economics': ['Poverty & Inequality', 'Economic Growth', 'Institutions', 'Development Finance', 'Health & Education'],
    'Public Economics': ['Taxation', 'Public Goods', 'Social Insurance', 'Political Economy', 'Cost-Benefit Analysis'],
    'Urban & Regional Economics': ['Urban Growth', 'Agglomeration', 'Housing Economics', 'Local Public Finance', 'Regional Inequality'],
    'Environmental & Resource Economics': ['Externalities', 'Carbon Pricing', 'Natural Resource Management', 'Environmental Valuation', 'Climate Economics'],
    'Health Economics': ['Health Insurance', 'Healthcare Markets', 'Pharmaceutical Economics', 'Value of Life', 'Health Inequality'],
  },
  'Finance': {
    'Asset Pricing': ['Equity Pricing', 'Fixed Income', 'Factor Models', 'Stochastic Discount Factors', 'Empirical Asset Pricing'],
    'Corporate Finance': ['Capital Structure', 'Corporate Governance', 'Mergers & Acquisitions', 'Venture Capital'],
    'Derivatives & Options': ['Options Pricing', 'Futures & Forwards', 'Interest Rate Derivatives', 'Credit Derivatives'],
    'Portfolio Theory': ['Mean-Variance Optimization', 'CAPM', 'Multi-Factor Models', 'Alternative Investments'],
    'Behavioral Finance': ['Investor Biases', 'Market Anomalies', 'Noise Trading', 'Sentiment'],
    'Financial Econometrics': ['GARCH Models', 'High-Frequency Data', 'Volatility Modeling', 'Cointegration'],
    'Risk Management': ['Value at Risk', 'Credit Risk', 'Systemic Risk', 'Stress Testing'],
    'Market Microstructure': ['Order Flow', 'Market Making', 'Price Discovery', 'Algorithmic Trading'],
  },
  'Psychology': {
    'Cognitive Psychology': ['Perception', 'Attention', 'Memory', 'Problem Solving', 'Language Processing', 'Judgment & Decision Making'],
    'Social Psychology': ['Attitudes & Persuasion', 'Group Dynamics', 'Social Cognition', 'Prejudice & Discrimination', 'Conformity'],
    'Developmental Psychology': ['Cognitive Development', 'Social Development', 'Language Acquisition', 'Attachment Theory'],
    'Clinical Psychology': ['Psychopathology', 'Cognitive-Behavioral Therapy', 'Psychodynamic Theory', 'Assessment'],
    'Personality Psychology': ['Trait Theory', 'Personality Assessment', 'Personality Disorders', 'Personality & Behavior'],
    'Neuropsychology': ['Brain-Behavior Relationships', 'Cognitive Rehabilitation', 'Neuropsychological Assessment'],
    'Evolutionary Psychology': ['Adaptation', 'Mating & Reproduction', 'Kinship & Cooperation', 'Evolved Cognition'],
    'Positive Psychology': ['Well-Being', 'Resilience', 'Character Strengths', 'Mindfulness', 'Flow'],
    'Industrial-Organizational Psychology': ['Personnel Selection', 'Work Motivation', 'Leadership', 'Organizational Development', 'Job Performance'],
    'Health Psychology': ['Stress & Health', 'Health Behavior Change', 'Chronic Illness', 'Pain Psychology', 'Psychoneuroimmunology'],
    'Psychometrics': ['Test Theory', 'Item Response Theory', 'Factor Analysis', 'Psychological Measurement', 'Test Validity'],
  },
  'Sociology': {
    'Social Theory': ['Classical Theory', 'Contemporary Theory', 'Critical Theory', 'Structuralism', 'Symbolic Interactionism'],
    'Stratification & Inequality': ['Class & Status', 'Social Mobility', 'Poverty', 'Wealth & Income Inequality'],
    'Organizations': ['Organizational Theory', 'Work & Occupations', 'Bureaucracy', 'Institutional Theory'],
    'Political Sociology': ['State & Society', 'Social Movements', 'Power & Authority', 'Democracy & Civil Society'],
    'Cultural Sociology': ['Culture & Society', 'Religion & Society', 'Media & Culture', 'Consumption'],
    'Demography': ['Population Growth', 'Migration', 'Fertility & Mortality', 'Aging'],
    'Urban Sociology': ['City & Society', 'Gentrification', 'Segregation', 'Urban Poverty'],
    'Race & Ethnicity': ['Racial Formation', 'Ethnic Identity', 'Racism & Discrimination', 'Multiculturalism'],
    'Medical Sociology': ['Sick Role', 'Healthcare Systems', 'Medicalization', 'Health Disparities', 'Mental Illness & Society'],
    'Economic Sociology': ['Markets & Society', 'Economic Institutions', 'Social Capital', 'Networks & Exchange', 'Financialization'],
    'Environmental Sociology': ['Society & Nature', 'Environmental Justice', 'Climate Change & Society', 'Risk Society', 'Political Ecology'],
    'Sociology of Knowledge & Science': ['Social Construction of Knowledge', 'Science & Technology Studies', 'Epistemology of Social Science'],
  },
  'Political Science': {
    'Political Theory': ['Liberal Theory', 'Democratic Theory', 'Justice & Rights', 'Republicanism', 'Critical Theory'],
    'Comparative Politics': ['Democratization', 'Authoritarianism', 'Electoral Systems', 'Political Parties', 'State Building'],
    'International Relations': ['Realism', 'Liberalism', 'Constructivism', 'International Security', 'International Political Economy'],
    'Public Policy': ['Policy Analysis', 'Agenda Setting', 'Regulatory Policy', 'Social Policy', 'Implementation'],
    'Political Economy': ['Varieties of Capitalism', 'Globalization', 'Development', 'Political Business Cycles'],
    'Conflict & Peace Studies': ['War & Peace', 'Civil War', 'Terrorism', 'Peacekeeping', 'Conflict Resolution'],
    'Electoral Politics': ['Voting Behavior', 'Electoral Systems', 'Campaign Finance', 'Public Opinion'],
    'Democratic Theory': ['Deliberative Democracy', 'Participatory Democracy', 'Electoral Democracy', 'Populism'],
  },
  'Anthropology': {
    'Cultural Anthropology': ['Ethnography', 'Kinship & Family', 'Religion & Ritual', 'Economic Anthropology', 'Political Anthropology'],
    'Biological Anthropology': ['Human Evolution', 'Primatology', 'Paleoanthropology', 'Forensic Anthropology'],
    'Archaeology': ['Prehistoric Archaeology', 'Classical Archaeology', 'Archaeological Theory', 'Landscape Archaeology'],
    'Linguistic Anthropology': ['Language & Culture', 'Ethnolinguistics', 'Language Endangerment', 'Discourse Analysis'],
    'Medical Anthropology': ['Illness & Healing', 'Biomedicine & Culture', 'Mental Health', 'Global Health'],
    'Economic Anthropology': ['Exchange & Reciprocity', 'Markets & Capitalism', 'Peasant Studies', 'Development & Anthropology'],
  },
  'History': {
    'Ancient History': ['Ancient Near East', 'Classical Greece', 'Roman History', 'Ancient China', 'Ancient Egypt'],
    'Medieval History': ['Byzantine Empire', 'Islamic World', 'European Middle Ages', 'Medieval China', 'Crusades'],
    'Early Modern History': ['Renaissance', 'Reformation', 'Scientific Revolution', 'Age of Exploration', 'Early Modern Europe'],
    'Modern History': ['French Revolution', 'Industrial Revolution', 'Colonialism & Imperialism', 'World Wars', 'Cold War'],
    'Intellectual History': ['History of Ideas', 'History of Science', 'History of Philosophy', 'History of Religion'],
    'Social History': ['Labor History', 'Gender History', 'Family History', 'History of Everyday Life'],
    'Economic History': ['Commercial Revolution', 'Industrialization', 'Global Economic History', 'Financial History'],
    'Historiography': ['Historical Method', 'Philosophy of History', 'Schools of Historiography', 'Oral History'],
    'Environmental History': ['Climate & Civilization', 'Nature & Culture', 'Disease & History', 'Conservation History', 'Environmental Change'],
    'Military History': ['Strategy & Warfare', 'Military Technology', 'War & Society', 'Naval History', 'Counterinsurgency'],
    'Global & Postcolonial History': ['World-Systems Theory', 'Connected Histories', 'Decolonization', 'Postcolonial Critique', 'Transnational History'],
    'Digital History': ['Historical Data Analysis', 'Digital Archives', 'Computational History', 'Public History & Digital Media'],
  },
  'Philosophy': {
    'Metaphysics': ['Ontology', 'Philosophy of Time', 'Personal Identity', 'Causation', 'Free Will & Determinism'],
    'Epistemology': ['Knowledge & Justification', 'Skepticism', 'Philosophy of Perception', 'Social Epistemology'],
    'Ethics': ['Metaethics', 'Normative Ethics', 'Applied Ethics', 'Moral Psychology', 'Environmental Ethics'],
    'Philosophy of Mind': ['Consciousness', 'Mental Causation', 'Intentionality', 'Philosophy of Cognitive Science'],
    'Philosophy of Language': ['Meaning & Reference', 'Speech Act Theory', 'Truth & Paradox', 'Pragmatics'],
    'Philosophy of Science': ['Scientific Realism', 'Philosophy of Physics', 'Philosophy of Biology', 'Confirmation & Explanation'],
    'Political Philosophy': ['Justice', 'Liberty & Equality', 'Democracy', 'Global Justice', 'Distributive Justice'],
    'Logic': ['Classical Logic', 'Modal Logic', 'Non-Classical Logics', 'Formal Semantics', 'Philosophical Logic'],
    'Aesthetics': ['Philosophy of Art', 'Philosophy of Music', 'Literary Aesthetics', 'Beauty & Taste'],
    'Philosophy of Mathematics': ['Platonism & Anti-Platonism', 'Structuralism', 'Intuitionism', 'Philosophy of Proof', 'Logicism'],
    'Bioethics & Ethics of Technology': ['Medical Ethics', 'AI Ethics', 'Research Ethics', 'Environmental Ethics', 'Neuroethics'],
    'Philosophy of Action': ['Intention & Agency', 'Practical Reason', 'Akrasia', 'Collective Action', 'Moral Responsibility'],
    'Continental Philosophy': ['Phenomenology', 'Existentialism', 'Hermeneutics', 'Critical Theory', 'Poststructuralism'],
  },
  'Linguistics': {
    'Phonology': ['Phonological Theory', 'Prosody', 'Laboratory Phonology', 'Autosegmental Phonology'],
    'Morphology': ['Morphological Theory', 'Inflection', 'Word Formation', 'Morphophonology'],
    'Syntax': ['Generative Syntax', 'Functional Syntax', 'Construction Grammar', 'Dependency Grammar'],
    'Semantics': ['Formal Semantics', 'Lexical Semantics', 'Compositional Semantics', 'Cognitive Semantics'],
    'Pragmatics': ['Implicature', 'Speech Acts', 'Discourse Analysis', 'Relevance Theory'],
    'Sociolinguistics': ['Language Variation', 'Language Change', 'Language Policy', 'Bilingualism'],
    'Historical Linguistics': ['Language Change', 'Comparative Method', 'Language Families', 'Etymology'],
    'Psycholinguistics': ['Language Acquisition', 'Language Processing', 'Bilingual Processing', 'Aphasia'],
    'Computational Linguistics': ['Parsing', 'Machine Translation', 'Information Extraction', 'Computational Semantics'],
    'Corpus Linguistics': ['Corpus Design', 'Frequency & Collocation', 'Corpus-Based Grammar', 'Learner Corpora', 'Discourse Analysis'],
    'Neurolinguistics': ['Language & Brain', 'Aphasia & Disorders', 'Neural Basis of Grammar', 'Language Development & Brain'],
    'Sign Language Linguistics': ['Phonology of Sign', 'Sign Language Syntax', 'Spatial Grammar', 'Sign Language Typology'],
    'Language Typology': ['Linguistic Universals', 'Grammatical Categories', 'Cross-Linguistic Variation', 'Endangered Languages'],
  },
  'Literature & Literary Theory': {
    'Literary Criticism': ['New Criticism', 'Reader-Response Theory', 'Hermeneutics', 'Biographical Criticism'],
    'Narrative Theory': ['Narratology', 'Story & Discourse', 'Unreliable Narration', 'Temporal Structure'],
    'Postcolonial Theory': ['Orientalism', 'Colonial Discourse', 'Diaspora Studies', 'Subaltern Studies'],
    'Feminist Literary Theory': ['Gender & Writing', 'Écriture Féminine', 'Intersectionality', 'Queer Theory'],
    'Structuralism & Post-Structuralism': ['Semiotics', 'Deconstruction', 'Intertextuality', 'Discourse Theory'],
    'Genre Studies': ['The Novel', 'Poetry', 'Drama', 'Short Fiction', 'Epic & Romance'],
    'World Literature': ['Comparative Literature', 'Translation Studies', 'Postcolonial Literature', 'Global Literature'],
    'Poetry & Poetics': ['Lyric Theory', 'Prosody & Form', 'Modernist Poetry', 'Ecopoetics'],
    'Ecocriticism': ['Nature Writing', 'Environmental Literature', 'Cli-Fi', 'Posthumanism', 'Animal Studies'],
    'Digital Literature & Distant Reading': ['Computational Literary Studies', 'Cultural Analytics', 'Hypertext Fiction', 'Corpus Stylistics'],
    'Trauma & Memory Studies': ['Trauma Theory', 'Holocaust Literature', 'Memory & Narrative', 'Witness Literature'],
  },
  'Law': {
    'Constitutional Law': ['Judicial Review', 'Separation of Powers', 'Fundamental Rights', 'Federalism'],
    'Criminal Law': ['Criminal Liability', 'Punishment Theory', 'Criminal Procedure', 'Evidence'],
    'International Law': ['Public International Law', 'International Human Rights', 'International Humanitarian Law', 'Trade Law'],
    'Tort Law': ['Negligence', 'Strict Liability', 'Products Liability', 'Defamation'],
    'Contract Law': ['Formation & Validity', 'Breach & Remedies', 'Commercial Contracts', 'Consumer Contracts'],
    'Administrative Law': ['Regulatory Theory', 'Judicial Review of Administration', 'Delegation', 'Agency Law'],
    'Legal Theory & Jurisprudence': ['Natural Law', 'Legal Positivism', 'Critical Legal Studies', 'Law & Economics'],
    'Property Law': ['Real Property', 'Intellectual Property', 'Property Theory', 'Trusts & Estates'],
    'Human Rights Law': ['International Human Rights', 'Humanitarian Law', 'Refugee Law', 'Economic & Social Rights'],
    'Family Law': ['Marriage & Divorce', 'Child Custody', 'Adoption', 'Domestic Violence Law', 'Reproductive Rights'],
    'Environmental Law': ['Climate Law', 'Pollution Control', 'Natural Resource Law', 'International Environmental Law', 'Environmental Justice'],
    'Tax Law': ['Income Taxation', 'Corporate Tax', 'International Tax', 'Tax Policy', 'Wealth & Transfer Taxes'],
    'Comparative Law': ['Legal Families', 'Comparative Constitutional Law', 'Mixed Legal Systems', 'Legal Transplants', 'Comparative Private Law'],
    'Commercial & Corporate Law': ['Company Law', 'Securities Regulation', 'Bankruptcy Law', 'Consumer Protection', 'Competition Law'],
  },
  'Medicine & Health Sciences': {
    'Anatomy & Physiology': ['Gross Anatomy', 'Neuroanatomy', 'Cardiovascular Physiology', 'Respiratory Physiology'],
    'Pathology': ['General Pathology', 'Systemic Pathology', 'Molecular Pathology', 'Forensic Pathology'],
    'Pharmacology': ['Pharmacokinetics', 'Pharmacodynamics', 'Clinical Pharmacology', 'Drug Discovery'],
    'Epidemiology': ['Disease Epidemiology', 'Clinical Epidemiology', 'Genetic Epidemiology', 'Environmental Epidemiology'],
    'Public Health': ['Global Health', 'Health Policy', 'Social Determinants of Health', 'Health Promotion'],
    'Medical Ethics': ['Bioethics', 'Clinical Ethics', 'Research Ethics', 'End-of-Life Ethics'],
    'Psychiatry': ['Mood Disorders', 'Psychotic Disorders', 'Anxiety Disorders', 'Neurodevelopmental Disorders'],
    'Oncology': ['Cancer Biology', 'Cancer Therapy', 'Immunotherapy', 'Cancer Epidemiology'],
    'Infectious Disease': ['Bacteriology', 'Virology', 'Parasitology', 'Antimicrobial Resistance'],
  },
  'Earth & Environmental Science': {
    'Geology': ['Mineralogy', 'Petrology', 'Structural Geology', 'Geomorphology', 'Stratigraphy'],
    'Climatology': ['Climate Dynamics', 'Climate Change', 'Paleoclimatology', 'Regional Climatology'],
    'Oceanography': ['Physical Oceanography', 'Chemical Oceanography', 'Marine Biology', 'Deep-Sea Science'],
    'Atmospheric Science': ['Atmospheric Dynamics', 'Atmospheric Chemistry', 'Meteorology', 'Aeronomy'],
    'Environmental Science': ['Pollution & Remediation', 'Conservation Science', 'Sustainability Science', 'Environmental Policy'],
    'Ecology': ['Population Ecology', 'Community Ecology', 'Ecosystem Ecology', 'Global Ecology'],
    'Geophysics': ['Seismology', 'Geomagnetism', 'Geodesy', 'Volcanology'],
    'Paleontology': ['Vertebrate Paleontology', 'Invertebrate Paleontology', 'Paleoecology', 'Astrobiology'],
  },
  'Engineering': {
    'Electrical Engineering': ['Circuits & Electronics', 'Signal Processing', 'Power Systems', 'Electromagnetics', 'Semiconductor Devices'],
    'Mechanical Engineering': ['Solid Mechanics', 'Thermodynamics & Heat Transfer', 'Fluid Mechanics', 'Manufacturing', 'Robotics & Mechatronics'],
    'Civil Engineering': ['Structural Engineering', 'Geotechnical Engineering', 'Transportation Engineering', 'Hydraulics', 'Environmental Engineering'],
    'Chemical Engineering': ['Transport Phenomena', 'Reaction Engineering', 'Separation Processes', 'Process Control'],
    'Biomedical Engineering': ['Biomechanics', 'Biomedical Imaging', 'Tissue Engineering', 'Neural Engineering'],
    'Materials Science': ['Metals & Alloys', 'Polymers', 'Ceramics', 'Nanomaterials', 'Electronic Materials'],
    'Aerospace Engineering': ['Aerodynamics', 'Propulsion', 'Spacecraft Design', 'Orbital Mechanics'],
    'Control Systems': ['Classical Control', 'Modern Control Theory', 'Optimal Control', 'Robust Control'],
    'Industrial Engineering': ['Operations Research', 'Supply Chain Management', 'Human Factors', 'Quality Engineering', 'Systems Engineering'],
    'Energy Engineering': ['Renewable Energy Systems', 'Nuclear Engineering', 'Energy Storage', 'Smart Grids', 'Thermodynamic Power Cycles'],
  },
  'Education': {
    'Philosophy of Education': ['Educational Aims & Values', 'Critical Pedagogy', 'Pragmatism & Education', 'Democratic Education'],
    'Educational Psychology': ['Learning Theories', 'Motivation & Self-Regulation', 'Cognitive Development & Learning', 'Assessment & Measurement'],
    'Curriculum & Instruction': ['Curriculum Theory', 'Instructional Design', 'STEM Education', 'Literacy Education', 'Humanities Education'],
    'Higher Education': ['Academic Profession', 'Student Development', 'University Governance', 'Graduate Education', 'College Completion'],
    'Educational Technology': ['E-Learning', 'Instructional Technology', 'Learning Analytics', 'Educational Games', 'Digital Pedagogy'],
    'Special Education': ['Inclusive Education', 'Learning Disabilities', 'Gifted Education', 'Autism Spectrum', 'Behavioral Interventions'],
    'Comparative & International Education': ['Education Policy', 'Global Schooling', 'Educational Equity', 'PISA & International Assessments'],
    'Adult & Lifelong Learning': ['Adult Literacy', 'Workplace Learning', 'Community Education', 'Non-Formal Education'],
  },
  'Geography & Geospatial Sciences': {
    'Physical Geography': ['Geomorphology', 'Climatology', 'Hydrology', 'Biogeography', 'Glaciology'],
    'Human Geography': ['Urban Geography', 'Economic Geography', 'Political Geography', 'Cultural Geography', 'Migration & Population'],
    'Environmental Geography': ['Human-Environment Interaction', 'Environmental Justice', 'Land Use & Land Cover', 'Natural Hazards'],
    'Geographic Information Science': ['Remote Sensing', 'Spatial Analysis', 'Cartography', 'Geographic Information Systems', 'Spatial Big Data'],
    'Regional Science': ['Regional Development', 'Spatial Economics', 'Location Theory', 'Urban & Regional Planning'],
    'Geopolitics': ['Territory & Sovereignty', 'Critical Geopolitics', 'Resource Geopolitics', 'Borders & Boundaries'],
  },
  'Communication & Media Studies': {
    'Mass Communication Theory': ['Agenda Setting', 'Framing Theory', 'Uses & Gratifications', 'Cultivation Theory', 'Two-Step Flow'],
    'Journalism Studies': ['News Production', 'Political Journalism', 'Investigative Journalism', 'Digital Journalism', 'Media Ethics'],
    'Rhetoric & Persuasion': ['Classical Rhetoric', 'Argumentation Theory', 'Political Communication', 'Discourse Analysis'],
    'Media Studies': ['Film Studies', 'Television Studies', 'Digital Media', 'Platform Studies', 'Media History'],
    'Interpersonal Communication': ['Conversation Analysis', 'Nonverbal Communication', 'Relational Communication', 'Organizational Communication'],
    'Science Communication': ['Public Understanding of Science', 'Risk Communication', 'Health Communication', 'Science Journalism'],
    'Advertising & Public Relations': ['Advertising Theory', 'Brand Communication', 'Crisis Communication', 'Propaganda Studies'],
  },
  'Religious Studies & Theology': {
    'Comparative Religion': ['World Religions Overview', 'Phenomenology of Religion', 'Ritual Studies', 'Mysticism', 'Sacred & Profane'],
    'Christian Theology': ['Systematic Theology', 'Biblical Studies', 'Patristics', 'Reformation Theology', 'Liberation Theology'],
    'Islamic Studies': ['Quran & Hadith', 'Islamic Law (Fiqh)', 'Islamic Philosophy', 'Sufism', 'Contemporary Islam'],
    'Jewish Studies': ['Talmud & Midrash', 'Kabbalah', 'Modern Jewish Thought', 'Holocaust Studies', 'Zionism & Israel'],
    'Buddhist Studies': ['Theravada Buddhism', 'Mahayana Buddhism', 'Zen & Chan', 'Tibetan Buddhism', 'Buddhist Ethics'],
    'Philosophy of Religion': ['Arguments for God', 'Problem of Evil', 'Religious Experience', 'Religion & Science', 'Religious Epistemology'],
    'Hindu Studies': ['Vedanta', 'Yoga Traditions', 'Bhakti', 'Hindu Ethics', 'Tantra'],
    'Sociology of Religion': ['Secularization', 'Religious Revival', 'New Religious Movements', 'Religion & Politics'],
  },
  'Architecture & Urban Design': {
    'Architectural Theory': ['Phenomenology of Space', 'Modernism & Post-Modernism', 'Critical Regionalism', 'Tectonics', 'Digital Architecture'],
    'Urban Design': ['Public Space', 'Urban Form', 'Transit-Oriented Development', 'New Urbanism', 'Landscape Urbanism'],
    'City & Regional Planning': ['Land Use Planning', 'Transportation Planning', 'Housing Policy', 'Zoning & Regulation', 'Smart Cities'],
    'Architectural History': ['Ancient & Classical', 'Renaissance & Baroque', 'Industrial Era', 'Modern Movement', 'Contemporary Architecture'],
    'Building Technology': ['Structural Systems', 'Environmental Systems', 'Sustainable Design', 'Building Information Modeling'],
    'Landscape Architecture': ['Ecological Design', 'Urban Parks', 'Cultural Landscapes', 'Green Infrastructure'],
    'Housing Studies': ['Affordable Housing', 'Housing Markets', 'Informal Settlements', 'Residential Design'],
  },
  'Music & Musicology': {
    'Music Theory': ['Harmony & Counterpoint', 'Form & Analysis', 'Post-Tonal Theory', 'Rhythm & Meter', 'Schenkerian Analysis'],
    'Music History': ['Medieval & Renaissance', 'Baroque', 'Classical & Romantic', '20th Century', 'Contemporary Music'],
    'Ethnomusicology': ['World Music Traditions', 'Music & Culture', 'Fieldwork Methods', 'Music & Identity', 'Organology'],
    'Music Cognition': ['Music Perception', 'Musical Memory', 'Emotion & Music', 'Music & Language', 'Computational Musicology'],
    'Performance Practice': ['Historical Performance', 'Improvisation', 'Conducting', 'Pedagogy & Training'],
    'Popular Music Studies': ['Rock & Roll', 'Hip-Hop Studies', 'Jazz Studies', 'Electronic Music', 'Music Industry'],
    'Music & Technology': ['Electroacoustic Music', 'Digital Audio', 'Music Information Retrieval', 'Sound Studies'],
  },
  'Art History & Visual Culture': {
    'Art History (Ancient–Medieval)': ['Ancient Near East', 'Greek & Roman Art', 'Byzantine Art', 'Medieval European Art', 'Islamic Art'],
    'Art History (Early Modern)': ['Italian Renaissance', 'Northern Renaissance', 'Baroque', 'Rococo', 'Neoclassicism'],
    'Art History (Modern)': ['Romanticism', 'Impressionism', 'Modernism', 'Avant-Garde Movements', 'Abstract Expressionism'],
    'Contemporary Art': ['Conceptual Art', 'Postmodernism', 'Installation Art', 'Performance Art', 'Digital Art'],
    'Visual Culture Studies': ['Image Theory', 'Media & Visuality', 'Photography Studies', 'Film Theory', 'Design History'],
    'Non-Western Art': ['East Asian Art', 'African Art', 'Indigenous Art', 'South Asian Art', 'Latin American Art'],
    'Curatorial Studies & Museum Theory': ['Museology', 'Exhibition History', 'Cultural Heritage', 'Art Market'],
  },
  'Gender & Sexuality Studies': {
    'Feminist Theory': ['Liberal Feminism', 'Radical Feminism', 'Socialist Feminism', 'Intersectionality', 'Third-Wave Feminism'],
    'Queer Theory': ['Queer Performativity', 'Heteronormativity', 'Queer History', 'Sexuality & Power'],
    'Trans Studies': ['Trans Identity', 'Trans Politics', 'Medical Discourses', 'Trans Feminism'],
    'Masculinity Studies': ['Hegemonic Masculinity', 'Men & Feminism', 'Race & Masculinity', 'Fatherhood'],
    'Gender & Law': ['Reproductive Rights', 'Gender Violence', 'Title IX', 'LGBTQ+ Rights'],
    'Gender & Labor': ['Care Work', 'Gender Pay Gap', 'Domestic Labor', 'Feminist Political Economy'],
    'Postcolonial Feminism': ['Decolonial Feminism', 'Global South Feminism', 'Development & Gender', 'Subaltern Women'],
  },
  'Management & Business': {
    'Strategic Management': ['Competitive Advantage', 'Resource-Based View', 'Dynamic Capabilities', 'Corporate Strategy', 'Business Models'],
    'Organizational Behavior': ['Motivation & Leadership', 'Group Dynamics', 'Organizational Culture', 'Organizational Change'],
    'Marketing': ['Consumer Behavior', 'Brand Management', 'Market Research', 'Digital Marketing', 'Services Marketing'],
    'Operations Management': ['Supply Chain', 'Lean & Six Sigma', 'Project Management', 'Service Operations', 'Inventory Management'],
    'Entrepreneurship & Innovation': ['Venture Creation', 'Innovation Management', 'Technology Entrepreneurship', 'Social Entrepreneurship'],
    'Accounting': ['Financial Accounting', 'Management Accounting', 'Auditing', 'Taxation', 'Accounting Theory'],
    'Management Science': ['Decision Analysis', 'Optimization', 'Simulation', 'Forecasting', 'Risk Analysis'],
    'Business Ethics & Sustainability': ['Corporate Social Responsibility', 'Stakeholder Theory', 'ESG', 'Business & Human Rights'],
  },
  'Criminology & Criminal Justice': {
    'Criminological Theory': ['Classical School', 'Strain Theory', 'Social Learning', 'Control Theory', 'Critical Criminology'],
    'Crime Types': ['Violent Crime', 'Property Crime', 'White-Collar Crime', 'Cybercrime', 'Organized Crime'],
    'Criminal Justice System': ['Police Studies', 'Courts & Prosecution', 'Sentencing', 'Corrections', 'Juvenile Justice'],
    'Penology': ['Punishment Theory', 'Prison Studies', 'Probation & Parole', 'Restorative Justice', 'Incarceration'],
    'Victimology': ['Victim Experience', 'Victim Support', 'Repeat Victimization', 'Domestic Violence'],
    'Forensic Science': ['Forensic Biology', 'Forensic Psychology', 'Digital Forensics', 'Crime Scene Investigation'],
    'Security Studies': ['Terrorism', 'Counter-Terrorism', 'Intelligence Studies', 'Homeland Security', 'Cybersecurity'],
  },
  'Information Science': {
    'Information Retrieval': ['Search Engines', 'Text Mining', 'Query Processing', 'Relevance Ranking', 'Knowledge Retrieval'],
    'Knowledge Organization': ['Classification Systems', 'Ontologies', 'Metadata', 'Cataloging & Indexing', 'Taxonomy Design'],
    'Human Information Behavior': ['Information Seeking', 'Information Literacy', 'Sense-Making', 'Collaborative Information'],
    'Digital Libraries': ['Digital Preservation', 'Open Access', 'Institutional Repositories', 'Digital Humanities'],
    'Scientometrics & Bibliometrics': ['Citation Analysis', 'H-Index & Metrics', 'Research Evaluation', 'Science Mapping'],
    'Data Science & Analytics': ['Data Mining', 'Big Data', 'Data Visualization', 'Predictive Analytics', 'Knowledge Discovery'],
  },
  'Cognitive Science': {
    'Philosophy of Mind': ['Consciousness & Qualia', 'Mental Representation', 'Embodied Cognition', 'Intentionality', 'Extended Mind'],
    'Cognitive Psychology': ['Attention & Memory', 'Concepts & Categories', 'Reasoning & Judgment', 'Problem Solving', 'Mental Imagery'],
    'Cognitive Linguistics': ['Conceptual Metaphor', 'Construction Grammar', 'Prototype Theory', 'Spatial Language', 'Cognitive Semantics'],
    'Computational Modeling of Cognition': ['Connectionism', 'Symbolic AI', 'Bayesian Models of Cognition', 'Neural Networks & Mind'],
    'Developmental Cognitive Science': ['Core Knowledge', 'Theory of Mind', 'Concept Acquisition', 'Language Development'],
    'Social Cognition': ['Theory of Mind', 'Empathy', 'Social Perception', 'Cultural Cognition', 'Collective Intentionality'],
    'Cognitive Neuroscience': ['Neural Correlates of Cognition', 'Attention & Brain', 'Memory Systems', 'Decision & Reward'],
  },
  'Operations Research': {
    'Linear & Integer Programming': ['Simplex Method', 'Branch & Bound', 'Integer Optimization', 'Network Flow'],
    'Stochastic Optimization': ['Stochastic Programming', 'Robust Optimization', 'Chance Constraints', 'Scenario Analysis'],
    'Combinatorial Optimization': ['Traveling Salesman Problem', 'Graph Optimization', 'Scheduling Theory', 'Matching Theory'],
    'Queueing Theory': ['M/M/1 Queues', 'Priority Queues', 'Networks of Queues', 'Service Systems'],
    'Dynamic Programming': ['Bellman Equations', 'Markov Decision Processes', 'Approximate Dynamic Programming'],
    'Game Theory & Decision Theory': ['Utility Theory', 'Cooperative Games', 'Mechanism Design', 'Multi-Criteria Decision Making'],
    'Simulation': ['Discrete-Event Simulation', 'Monte Carlo Simulation', 'Agent-Based Simulation', 'Systems Dynamics'],
  },
  'Complex Systems & Network Science': {
    'Complexity Theory': ['Emergence', 'Self-Organization', 'Adaptive Systems', 'Edge of Chaos', 'Complexity & Evolution'],
    'Network Science': ['Graph Theory & Networks', 'Scale-Free Networks', 'Small-World Networks', 'Community Detection', 'Robustness'],
    'Dynamical Systems': ['Chaos Theory', 'Bifurcation Theory', 'Synchronization', 'Attractor Dynamics', 'Phase Transitions'],
    'Agent-Based Modeling': ['Cellular Automata', 'Evolutionary Computation', 'Artificial Life', 'Social Simulation'],
    'Information Theory': ['Entropy & Information', 'Channel Capacity', 'Coding Theory', 'Algorithmic Information Theory'],
    'Systems Biology & Biocomplexity': ['Gene Regulatory Networks', 'Metabolic Networks', 'Ecological Networks', 'Epidemics on Networks'],
  },
  'Agriculture & Food Science': {
    'Agronomy & Crop Science': ['Crop Physiology', 'Soil Science', 'Plant Breeding', 'Sustainable Agriculture', 'Precision Agriculture'],
    'Animal Science': ['Animal Nutrition', 'Animal Genetics', 'Livestock Management', 'Aquaculture', 'Animal Welfare'],
    'Food Science & Technology': ['Food Chemistry', 'Food Microbiology', 'Food Processing', 'Food Safety', 'Sensory Science'],
    'Agricultural Economics': ['Farm Management', 'Agricultural Policy', 'Food Markets', 'Rural Development', 'Agricultural Trade'],
    'Horticulture': ['Vegetable Crops', 'Fruit Science', 'Ornamental Horticulture', 'Post-Harvest Biology', 'Urban Agriculture'],
    'Soil Science': ['Soil Physics', 'Soil Chemistry', 'Soil Biology', 'Soil Fertility', 'Soil Conservation'],
    'Plant Pathology': ['Plant Diseases', 'Biocontrol', 'Integrated Pest Management', 'Epidemiology of Plant Disease'],
    'Agroecology': ['Ecological Farming', 'Biodiversity in Agriculture', 'Traditional Farming Systems', 'Food Systems'],
  },
  'Public Administration': {
    'Public Management': ['Administrative Theory', 'Performance Management', 'Public Sector Reform', 'Bureaucracy', 'E-Government'],
    'Policy Analysis & Design': ['Policy Instruments', 'Evaluation Methods', 'Evidence-Based Policy', 'Regulatory Impact Analysis'],
    'Public Budgeting & Finance': ['Government Budgeting', 'Public Debt', 'Fiscal Federalism', 'Revenue Administration'],
    'Governance & Democratic Administration': ['Accountability', 'Transparency', 'Participatory Governance', 'Anti-Corruption'],
    'Non-Profit & Third Sector Management': ['Non-Profit Governance', 'Philanthropy', 'Social Enterprise', 'Voluntary Sector'],
    'International Public Administration': ['Global Governance', 'International Organizations', 'Development Administration', 'Comparative Administration'],
  },
  'Sports Science & Kinesiology': {
    'Exercise Physiology': ['Cardiovascular Physiology', 'Muscle Physiology', 'Energy Metabolism', 'Environmental Physiology', 'Training Adaptation'],
    'Biomechanics': ['Human Movement Analysis', 'Sports Biomechanics', 'Orthopaedic Biomechanics', 'Motor Control', 'Gait Analysis'],
    'Sport & Exercise Psychology': ['Motivation in Sport', 'Anxiety & Performance', 'Team Cohesion', 'Mental Skills Training', 'Exercise & Well-Being'],
    'Sport Nutrition': ['Energy Availability', 'Macronutrient Strategies', 'Hydration', 'Ergogenic Aids', 'Weight Management in Sport'],
    'Physical Education & Pedagogy': ['PE Curriculum', 'Motor Skill Development', 'Physical Activity Promotion', 'Inclusive PE'],
    'Sports Medicine & Rehabilitation': ['Injury Prevention', 'Musculoskeletal Rehabilitation', 'Concussion', 'Return to Play', 'Sports Cardiology'],
    'Performance Science': ['Talent Identification', 'Periodization', 'Sports Analytics', 'High Performance Systems', 'Technology in Sport'],
  },
  'Social Work & Human Services': {
    'Social Work Theory & Methods': ['Systems Theory', 'Strengths-Based Practice', 'Psychosocial Approach', 'Ecological Perspective'],
    'Clinical Social Work': ['Psychotherapy', 'Trauma-Informed Practice', 'Mental Health Intervention', 'Substance Use Treatment'],
    'Child & Family Welfare': ['Child Protection', 'Foster Care', 'Family Intervention', 'Adoption', 'Youth Development'],
    'Community Practice': ['Community Organizing', 'Social Planning', 'Community Development', 'Policy Advocacy'],
    'Gerontological Social Work': ['Aging & Society', 'Elder Care', 'Dementia Care', 'End-of-Life', 'Intergenerational Practice'],
    'Social Policy': ['Welfare State', 'Social Security', 'Housing Policy', 'Poverty Policy', 'Comparative Social Policy'],
    'International Social Work': ['Global Social Issues', 'Refugee Services', 'Human Trafficking', 'Development Social Work'],
  },
  'Environmental Studies & Sustainability': {
    'Environmental Policy': ['Environmental Governance', 'International Environmental Agreements', 'Regulatory Design', 'Environmental Justice'],
    'Sustainability Science': ['Sustainable Development', 'Planetary Boundaries', 'Resilience Theory', 'Socio-Ecological Systems'],
    'Climate Change Studies': ['Climate Impacts', 'Mitigation Strategies', 'Adaptation Policy', 'Climate Justice', 'Carbon Markets'],
    'Ecological Economics': ['Natural Capital', 'Ecosystem Services', 'Degrowth', 'Steady-State Economics', 'Green Economy'],
    'Energy Policy & Transitions': ['Renewable Energy Policy', 'Energy Security', 'Just Transition', 'Energy Democracy', 'Decarbonization'],
    'Environmental Ethics & Philosophy': ['Deep Ecology', 'Environmental Justice', 'Intergenerational Ethics', 'Rights of Nature'],
    'Conservation Biology': ['Biodiversity Loss', 'Habitat Restoration', 'Protected Areas', 'Species Conservation', 'One Health'],
  },
  'Digital Humanities': {
    'Computational Text Analysis': ['Text Mining', 'Stylometry', 'Sentiment Analysis', 'Topic Modeling', 'Cultural Analytics'],
    'Digital Archives & Editions': ['Digital Preservation', 'Scholarly Editing', 'Metadata Standards', 'Linked Data', 'Digital Collections'],
    'Spatial Humanities': ['Historical GIS', 'Literary Geography', 'Digital Mapping', 'Spatial Analysis of Culture'],
    'Digital Art History': ['Image Analysis', 'Museum Informatics', '3D Visualization', 'Network Analysis in Art History'],
    'Data Visualization for Humanities': ['Network Visualization', 'Timeline Tools', 'Humanistic Data', 'Visual Arguments'],
    'Critical Digital Studies': ['Algorithmic Bias', 'Digital Labor', 'Surveillance Studies', 'Platform Criticism', 'Digital Ethics'],
  },
  'International & Area Studies': {
    'East Asian Studies': ['Chinese Studies', 'Japanese Studies', 'Korean Studies', 'East Asian Politics', 'East Asian Economies'],
    'South Asian Studies': ['Indian Studies', 'South Asian Politics', 'South Asian Religions', 'Postcolonial South Asia', 'South Asian Diaspora'],
    'Middle Eastern Studies': ['Arab World', 'Persian Studies', 'Islamic Civilization', 'Israeli Studies', 'Middle Eastern Politics'],
    'African Studies': ['African History', 'African Politics', 'African Economies', 'Sub-Saharan Africa', 'North Africa'],
    'Latin American Studies': ['Latin American History', 'Latin American Politics', 'Colonial Latin America', 'Indigenous Studies', 'Latin American Literature'],
    'European Studies': ['European Integration', 'European Politics', 'European History', 'Eastern Europe', 'European Culture'],
    'Development Studies': ['Development Theory', 'Global Poverty', 'Aid & Humanitarian Policy', 'Post-Development', 'South-South Cooperation'],
    'Global Studies': ['Globalization Theory', 'World-Systems Analysis', 'Transnational Movements', 'Global Civil Society'],
  },
};

// Flat list of top-level fields (for sidebar ordering)
export const getSubfields = (field) => Object.keys(ACADEMIC_TAXONOMY[field] || {});
export const getSubSubfields = (field, subfield) => ACADEMIC_TAXONOMY[field]?.[subfield] || [];

