export const TOP_LEVEL_FIELDS = [
  'Mathematics',
  'Statistics & Probability',
  'Physics',
  'Chemistry',
  'Biology',
  'Neuroscience',
  'Computer Science',
  'Artificial Intelligence',
  'Economics',
  'Finance',
  'Psychology',
  'Sociology',
  'Political Science',
  'Anthropology',
  'History',
  'Philosophy',
  'Linguistics',
  'Literature & Literary Theory',
  'Law',
  'Medicine & Health Sciences',
  'Earth & Environmental Science',
  'Engineering',
];
