// Three-level taxonomy: field → subfield → sub-subfields
// All hardcoded for instant sidebar navigation with no API calls
export const ACADEMIC_TAXONOMY = {
  'Mathematics': {
    'Algebra': ['Group Theory', 'Ring Theory', 'Linear Algebra', 'Commutative Algebra', 'Homological Algebra', 'Representation Theory', 'Galois Theory'],
    'Analysis': ['Real Analysis', 'Complex Analysis', 'Functional Analysis', 'Harmonic Analysis', 'Measure Theory', 'Calculus of Variations'],
    'Topology': ['Algebraic Topology', 'Differential Topology', 'General Topology', 'Geometric Topology', 'Knot Theory'],
    'Geometry': ['Differential Geometry', 'Algebraic Geometry', 'Riemannian Geometry', 'Symplectic Geometry', 'Discrete Geometry'],
    'Number Theory': ['Analytic Number Theory', 'Algebraic Number Theory', 'Arithmetic Geometry', 'Combinatorial Number Theory', 'Modular Forms'],
    'Combinatorics': ['Graph Theory', 'Enumerative Combinatorics', 'Extremal Combinatorics', 'Probabilistic Combinatorics', 'Matroid Theory'],
    'Logic & Foundations': ['Mathematical Logic', 'Set Theory', 'Model Theory', 'Proof Theory', 'Category Theory', 'Computability Theory'],
    'Probability Theory': ['Stochastic Calculus', 'Martingale Theory', 'Large Deviations', 'Random Graphs', 'Stochastic Processes'],
    'Differential Equations': ['Ordinary Differential Equations', 'Partial Differential Equations', 'Dynamical Systems', 'Chaos Theory'],
    'Numerical Analysis': ['Numerical Linear Algebra', 'Finite Element Methods', 'Numerical Optimization', 'Approximation Theory'],
  },
  'Statistics & Probability': {
    'Bayesian Statistics': ['Bayesian Inference', 'Bayesian Computation', 'Bayesian Nonparametrics', 'Hierarchical Models'],
    'Statistical Learning': ['Supervised Learning', 'Unsupervised Learning', 'Statistical Decision Theory', 'High-Dimensional Statistics'],
    'Stochastic Processes': ['Markov Chains', 'Brownian Motion', 'Point Processes', 'Random Fields'],
    'Time Series Analysis': ['ARIMA Models', 'State Space Models', 'Spectral Analysis', 'Forecasting'],
    'Causal Inference': ['Potential Outcomes Framework', 'Structural Causal Models', 'Instrumental Variables', 'Regression Discontinuity'],
    'Experimental Design': ['Randomized Controlled Trials', 'Factorial Designs', 'Adaptive Designs', 'A/B Testing'],
    'Multivariate Analysis': ['Principal Component Analysis', 'Factor Analysis', 'Cluster Analysis', 'Discriminant Analysis'],
    'Nonparametric Statistics': ['Rank Tests', 'Kernel Methods', 'Bootstrap Methods', 'Permutation Tests'],
  },
  'Physics': {
    'Classical Mechanics': ['Lagrangian Mechanics', 'Hamiltonian Mechanics', 'Celestial Mechanics', 'Fluid Dynamics', 'Chaos & Nonlinear Dynamics'],
    'Quantum Mechanics': ['Quantum Information', 'Quantum Computing', 'Scattering Theory', 'Many-Body Quantum Mechanics', 'Quantum Optics'],
    'Statistical Mechanics': ['Thermodynamics', 'Phase Transitions', 'Kinetic Theory', 'Non-equilibrium Statistical Mechanics'],
    'Electromagnetism': ['Classical Electrodynamics', 'Plasma Physics', 'Magnetohydrodynamics', 'Photonics'],
    'Quantum Field Theory': ['Gauge Theory', 'Renormalization', 'Conformal Field Theory', 'Topological Field Theory', 'String Theory'],
    'General Relativity': ['Black Hole Physics', 'Cosmology', 'Gravitational Waves', 'Quantum Gravity'],
    'Condensed Matter Physics': ['Solid State Physics', 'Superconductivity', 'Topological Phases', 'Strongly Correlated Systems'],
    'Particle Physics': ['Standard Model', 'Beyond the Standard Model', 'Collider Physics', 'Neutrino Physics'],
    'Astrophysics & Cosmology': ['Stellar Physics', 'Galactic Dynamics', 'Observational Cosmology', 'High-Energy Astrophysics'],
    'Optics': ['Nonlinear Optics', 'Laser Physics', 'Fiber Optics', 'Quantum Optics'],
  },
  'Chemistry': {
    'Organic Chemistry': ['Reaction Mechanisms', 'Synthetic Organic Chemistry', 'Stereochemistry', 'Natural Products Chemistry', 'Organocatalysis'],
    'Inorganic Chemistry': ['Coordination Chemistry', 'Organometallic Chemistry', 'Solid-State Chemistry', 'Bioinorganic Chemistry'],
    'Physical Chemistry': ['Quantum Chemistry', 'Chemical Thermodynamics', 'Chemical Kinetics', 'Spectroscopy', 'Surface Chemistry'],
    'Analytical Chemistry': ['Chromatography', 'Mass Spectrometry', 'Electroanalytical Chemistry', 'Spectroanalytical Methods'],
    'Biochemistry': ['Protein Biochemistry', 'Enzyme Kinetics', 'Metabolic Biochemistry', 'Nucleic Acid Biochemistry'],
    'Computational Chemistry': ['Density Functional Theory', 'Molecular Dynamics', 'Monte Carlo Methods', 'Cheminformatics'],
    'Materials Chemistry': ['Polymers', 'Nanomaterials', 'Electronic Materials', 'Biomaterials'],
    'Electrochemistry': ['Electrocatalysis', 'Electrochemical Energy Storage', 'Corrosion', 'Photoelectrochemistry'],
  },
  'Biology': {
    'Cell Biology': ['Cell Signaling', 'Cytoskeleton', 'Membrane Biology', 'Cell Division', 'Organelle Biology'],
    'Molecular Biology': ['Gene Expression', 'Epigenetics', 'RNA Biology', 'DNA Replication & Repair', 'Proteomics'],
    'Genetics': ['Classical Genetics', 'Population Genetics', 'Genomics', 'Quantitative Genetics', 'Genetic Engineering'],
    'Evolutionary Biology': ['Natural Selection', 'Phylogenetics', 'Speciation', 'Evolutionary Ecology', 'Evo-Devo'],
    'Ecology': ['Population Ecology', 'Community Ecology', 'Ecosystem Ecology', 'Conservation Biology', 'Behavioral Ecology'],
    'Developmental Biology': ['Embryology', 'Stem Cell Biology', 'Pattern Formation', 'Regeneration'],
    'Microbiology': ['Bacteriology', 'Virology', 'Mycology', 'Microbial Ecology', 'Microbial Genetics'],
    'Immunology': ['Innate Immunity', 'Adaptive Immunity', 'Immunopathology', 'Vaccinology', 'Tumor Immunology'],
    'Systems Biology': ['Gene Regulatory Networks', 'Metabolic Networks', 'Synthetic Biology', 'Bioinformatics'],
    'Structural Biology': ['X-ray Crystallography', 'Cryo-EM', 'NMR Spectroscopy', 'Protein Folding'],
  },
  'Neuroscience': {
    'Cognitive Neuroscience': ['Memory & Learning', 'Attention', 'Decision Making', 'Language & Brain', 'Consciousness'],
    'Computational Neuroscience': ['Neural Coding', 'Network Models', 'Theoretical Neuroscience', 'Connectomics'],
    'Molecular & Cellular Neuroscience': ['Synaptic Transmission', 'Ion Channels', 'Neuronal Development', 'Neuroplasticity'],
    'Systems Neuroscience': ['Sensory Systems', 'Motor Systems', 'Basal Ganglia', 'Hippocampus & Memory', 'Prefrontal Cortex'],
    'Behavioral Neuroscience': ['Learning & Memory', 'Motivation & Reward', 'Sleep & Circadian Rhythms', 'Stress & Emotion'],
    'Clinical Neuroscience': ['Neurodegenerative Diseases', 'Epilepsy', 'Psychiatric Disorders', 'Neurorehabilitation'],
  },
  'Computer Science': {
    'Algorithms & Data Structures': ['Sorting & Searching', 'Graph Algorithms', 'Dynamic Programming', 'Approximation Algorithms', 'Randomized Algorithms'],
    'Theory of Computation': ['Computability Theory', 'Complexity Theory', 'Automata Theory', 'Information Theory'],
    'Operating Systems': ['Process Management', 'Memory Management', 'File Systems', 'Concurrency'],
    'Computer Architecture': ['Processor Design', 'Memory Hierarchy', 'Parallel Architecture', 'GPU Architecture'],
    'Databases': ['Relational Databases', 'NoSQL Databases', 'Query Optimization', 'Distributed Databases', 'Data Warehousing'],
    'Computer Networks': ['Network Protocols', 'Internet Architecture', 'Wireless Networks', 'Network Security'],
    'Programming Languages': ['Type Theory', 'Compilers', 'Functional Programming', 'Program Analysis', 'Formal Verification'],
    'Software Engineering': ['Software Design Patterns', 'Testing & Verification', 'Agile Methods', 'Software Architecture'],
    'Computer Graphics': ['Rendering', 'Geometry Processing', 'Animation', 'Visualization'],
    'Distributed Systems': ['Consensus Algorithms', 'Fault Tolerance', 'Distributed Storage', 'Cloud Computing'],
    'Cryptography': ['Public-Key Cryptography', 'Symmetric Cryptography', 'Zero-Knowledge Proofs', 'Post-Quantum Cryptography'],
  },
  'Artificial Intelligence': {
    'Machine Learning': ['Supervised Learning', 'Unsupervised Learning', 'Semi-Supervised Learning', 'Ensemble Methods', 'Kernel Methods'],
    'Deep Learning': ['Convolutional Neural Networks', 'Recurrent Neural Networks', 'Transformers', 'Generative Adversarial Networks', 'Diffusion Models'],
    'Natural Language Processing': ['Language Models', 'Machine Translation', 'Information Extraction', 'Sentiment Analysis', 'Question Answering'],
    'Computer Vision': ['Object Detection', 'Image Segmentation', 'Visual Recognition', '3D Vision', 'Video Understanding'],
    'Reinforcement Learning': ['Model-Free RL', 'Model-Based RL', 'Multi-Agent RL', 'Reward Shaping', 'Hierarchical RL'],
    'Knowledge Representation': ['Ontologies', 'Knowledge Graphs', 'Logical Reasoning', 'Probabilistic Graphical Models'],
    'Robotics': ['Motion Planning', 'Robot Perception', 'Manipulation', 'Human-Robot Interaction', 'SLAM'],
    'AI Ethics & Safety': ['Fairness & Bias', 'Interpretability', 'AI Alignment', 'Privacy in ML', 'Robustness'],
    'Generative Models': ['Variational Autoencoders', 'Flow Models', 'Energy-Based Models', 'Foundation Models'],
  },
  'Economics': {
    'Microeconomics': ['Consumer Theory', 'Producer Theory', 'General Equilibrium', 'Information Economics', 'Contract Theory'],
    'Macroeconomics': ['Business Cycles', 'Monetary Economics', 'Fiscal Policy', 'Economic Growth', 'Open Economy Macroeconomics'],
    'Econometrics': ['Linear Models', 'Time Series Econometrics', 'Panel Data', 'Structural Estimation', 'Treatment Effects'],
    'Game Theory': ['Non-Cooperative Game Theory', 'Cooperative Game Theory', 'Mechanism Design', 'Evolutionary Game Theory'],
    'Behavioral Economics': ['Bounded Rationality', 'Prospect Theory', 'Social Preferences', 'Nudge Theory'],
    'Labor Economics': ['Human Capital', 'Labor Markets', 'Wage Determination', 'Labor Discrimination', 'Immigration'],
    'Industrial Organization': ['Market Structure', 'Antitrust Economics', 'Regulation', 'Platform Economics'],
    'International Economics': ['International Trade', 'Trade Policy', 'International Finance', 'Exchange Rates'],
    'Development Economics': ['Poverty & Inequality', 'Economic Growth', 'Institutions', 'Development Finance', 'Health & Education'],
    'Public Economics': ['Taxation', 'Public Goods', 'Social Insurance', 'Political Economy', 'Cost-Benefit Analysis'],
  },
  'Finance': {
    'Asset Pricing': ['Equity Pricing', 'Fixed Income', 'Factor Models', 'Stochastic Discount Factors', 'Empirical Asset Pricing'],
    'Corporate Finance': ['Capital Structure', 'Corporate Governance', 'Mergers & Acquisitions', 'Venture Capital'],
    'Derivatives & Options': ['Options Pricing', 'Futures & Forwards', 'Interest Rate Derivatives', 'Credit Derivatives'],
    'Portfolio Theory': ['Mean-Variance Optimization', 'CAPM', 'Multi-Factor Models', 'Alternative Investments'],
    'Behavioral Finance': ['Investor Biases', 'Market Anomalies', 'Noise Trading', 'Sentiment'],
    'Financial Econometrics': ['GARCH Models', 'High-Frequency Data', 'Volatility Modeling', 'Cointegration'],
    'Risk Management': ['Value at Risk', 'Credit Risk', 'Systemic Risk', 'Stress Testing'],
    'Market Microstructure': ['Order Flow', 'Market Making', 'Price Discovery', 'Algorithmic Trading'],
  },
  'Psychology': {
    'Cognitive Psychology': ['Perception', 'Attention', 'Memory', 'Problem Solving', 'Language Processing', 'Judgment & Decision Making'],
    'Social Psychology': ['Attitudes & Persuasion', 'Group Dynamics', 'Social Cognition', 'Prejudice & Discrimination', 'Conformity'],
    'Developmental Psychology': ['Cognitive Development', 'Social Development', 'Language Acquisition', 'Attachment Theory'],
    'Clinical Psychology': ['Psychopathology', 'Cognitive-Behavioral Therapy', 'Psychodynamic Theory', 'Assessment'],
    'Personality Psychology': ['Trait Theory', 'Personality Assessment', 'Personality Disorders', 'Personality & Behavior'],
    'Neuropsychology': ['Brain-Behavior Relationships', 'Cognitive Rehabilitation', 'Neuropsychological Assessment'],
    'Evolutionary Psychology': ['Adaptation', 'Mating & Reproduction', 'Kinship & Cooperation', 'Evolved Cognition'],
    'Positive Psychology': ['Well-Being', 'Resilience', 'Character Strengths', 'Mindfulness', 'Flow'],
  },
  'Sociology': {
    'Social Theory': ['Classical Theory', 'Contemporary Theory', 'Critical Theory', 'Structuralism', 'Symbolic Interactionism'],
    'Stratification & Inequality': ['Class & Status', 'Social Mobility', 'Poverty', 'Wealth & Income Inequality'],
    'Organizations': ['Organizational Theory', 'Work & Occupations', 'Bureaucracy', 'Institutional Theory'],
    'Political Sociology': ['State & Society', 'Social Movements', 'Power & Authority', 'Democracy & Civil Society'],
    'Cultural Sociology': ['Culture & Society', 'Religion & Society', 'Media & Culture', 'Consumption'],
    'Demography': ['Population Growth', 'Migration', 'Fertility & Mortality', 'Aging'],
    'Urban Sociology': ['City & Society', 'Gentrification', 'Segregation', 'Urban Poverty'],
    'Race & Ethnicity': ['Racial Formation', 'Ethnic Identity', 'Racism & Discrimination', 'Multiculturalism'],
  },
  'Political Science': {
    'Political Theory': ['Liberal Theory', 'Democratic Theory', 'Justice & Rights', 'Republicanism', 'Critical Theory'],
    'Comparative Politics': ['Democratization', 'Authoritarianism', 'Electoral Systems', 'Political Parties', 'State Building'],
    'International Relations': ['Realism', 'Liberalism', 'Constructivism', 'International Security', 'International Political Economy'],
    'Public Policy': ['Policy Analysis', 'Agenda Setting', 'Regulatory Policy', 'Social Policy', 'Implementation'],
    'Political Economy': ['Varieties of Capitalism', 'Globalization', 'Development', 'Political Business Cycles'],
    'Conflict & Peace Studies': ['War & Peace', 'Civil War', 'Terrorism', 'Peacekeeping', 'Conflict Resolution'],
    'Electoral Politics': ['Voting Behavior', 'Electoral Systems', 'Campaign Finance', 'Public Opinion'],
    'Democratic Theory': ['Deliberative Democracy', 'Participatory Democracy', 'Electoral Democracy', 'Populism'],
  },
  'Anthropology': {
    'Cultural Anthropology': ['Ethnography', 'Kinship & Family', 'Religion & Ritual', 'Economic Anthropology', 'Political Anthropology'],
    'Biological Anthropology': ['Human Evolution', 'Primatology', 'Paleoanthropology', 'Forensic Anthropology'],
    'Archaeology': ['Prehistoric Archaeology', 'Classical Archaeology', 'Archaeological Theory', 'Landscape Archaeology'],
    'Linguistic Anthropology': ['Language & Culture', 'Ethnolinguistics', 'Language Endangerment', 'Discourse Analysis'],
    'Medical Anthropology': ['Illness & Healing', 'Biomedicine & Culture', 'Mental Health', 'Global Health'],
    'Economic Anthropology': ['Exchange & Reciprocity', 'Markets & Capitalism', 'Peasant Studies', 'Development & Anthropology'],
  },
  'History': {
    'Ancient History': ['Ancient Near East', 'Classical Greece', 'Roman History', 'Ancient China', 'Ancient Egypt'],
    'Medieval History': ['Byzantine Empire', 'Islamic World', 'European Middle Ages', 'Medieval China', 'Crusades'],
    'Early Modern History': ['Renaissance', 'Reformation', 'Scientific Revolution', 'Age of Exploration', 'Early Modern Europe'],
    'Modern History': ['French Revolution', 'Industrial Revolution', 'Colonialism & Imperialism', 'World Wars', 'Cold War'],
    'Intellectual History': ['History of Ideas', 'History of Science', 'History of Philosophy', 'History of Religion'],
    'Social History': ['Labor History', 'Gender History', 'Family History', 'History of Everyday Life'],
    'Economic History': ['Commercial Revolution', 'Industrialization', 'Global Economic History', 'Financial History'],
    'Historiography': ['Historical Method', 'Philosophy of History', 'Schools of Historiography', 'Oral History'],
  },
  'Philosophy': {
    'Metaphysics': ['Ontology', 'Philosophy of Time', 'Personal Identity', 'Causation', 'Free Will & Determinism'],
    'Epistemology': ['Knowledge & Justification', 'Skepticism', 'Philosophy of Perception', 'Social Epistemology'],
    'Ethics': ['Metaethics', 'Normative Ethics', 'Applied Ethics', 'Moral Psychology', 'Environmental Ethics'],
    'Philosophy of Mind': ['Consciousness', 'Mental Causation', 'Intentionality', 'Philosophy of Cognitive Science'],
    'Philosophy of Language': ['Meaning & Reference', 'Speech Act Theory', 'Truth & Paradox', 'Pragmatics'],
    'Philosophy of Science': ['Scientific Realism', 'Philosophy of Physics', 'Philosophy of Biology', 'Confirmation & Explanation'],
    'Political Philosophy': ['Justice', 'Liberty & Equality', 'Democracy', 'Global Justice', 'Distributive Justice'],
    'Logic': ['Classical Logic', 'Modal Logic', 'Non-Classical Logics', 'Formal Semantics', 'Philosophical Logic'],
    'Aesthetics': ['Philosophy of Art', 'Philosophy of Music', 'Literary Aesthetics', 'Beauty & Taste'],
  },
  'Linguistics': {
    'Phonology': ['Phonological Theory', 'Prosody', 'Laboratory Phonology', 'Autosegmental Phonology'],
    'Morphology': ['Morphological Theory', 'Inflection', 'Word Formation', 'Morphophonology'],
    'Syntax': ['Generative Syntax', 'Functional Syntax', 'Construction Grammar', 'Dependency Grammar'],
    'Semantics': ['Formal Semantics', 'Lexical Semantics', 'Compositional Semantics', 'Cognitive Semantics'],
    'Pragmatics': ['Implicature', 'Speech Acts', 'Discourse Analysis', 'Relevance Theory'],
    'Sociolinguistics': ['Language Variation', 'Language Change', 'Language Policy', 'Bilingualism'],
    'Historical Linguistics': ['Language Change', 'Comparative Method', 'Language Families', 'Etymology'],
    'Psycholinguistics': ['Language Acquisition', 'Language Processing', 'Bilingual Processing', 'Aphasia'],
    'Computational Linguistics': ['Parsing', 'Machine Translation', 'Information Extraction', 'Computational Semantics'],
  },
  'Literature & Literary Theory': {
    'Literary Criticism': ['New Criticism', 'Reader-Response Theory', 'Hermeneutics', 'Biographical Criticism'],
    'Narrative Theory': ['Narratology', 'Story & Discourse', 'Unreliable Narration', 'Temporal Structure'],
    'Postcolonial Theory': ['Orientalism', 'Colonial Discourse', 'Diaspora Studies', 'Subaltern Studies'],
    'Feminist Literary Theory': ['Gender & Writing', 'Écriture Féminine', 'Intersectionality', 'Queer Theory'],
    'Structuralism & Post-Structuralism': ['Semiotics', 'Deconstruction', 'Intertextuality', 'Discourse Theory'],
    'Genre Studies': ['The Novel', 'Poetry', 'Drama', 'Short Fiction', 'Epic & Romance'],
    'World Literature': ['Comparative Literature', 'Translation Studies', 'Postcolonial Literature', 'Global Literature'],
    'Poetry & Poetics': ['Lyric Theory', 'Prosody & Form', 'Modernist Poetry', 'Ecopoetics'],
  },
  'Law': {
    'Constitutional Law': ['Judicial Review', 'Separation of Powers', 'Fundamental Rights', 'Federalism'],
    'Criminal Law': ['Criminal Liability', 'Punishment Theory', 'Criminal Procedure', 'Evidence'],
    'International Law': ['Public International Law', 'International Human Rights', 'International Humanitarian Law', 'Trade Law'],
    'Tort Law': ['Negligence', 'Strict Liability', 'Products Liability', 'Defamation'],
    'Contract Law': ['Formation & Validity', 'Breach & Remedies', 'Commercial Contracts', 'Consumer Contracts'],
    'Administrative Law': ['Regulatory Theory', 'Judicial Review of Administration', 'Delegation', 'Agency Law'],
    'Legal Theory & Jurisprudence': ['Natural Law', 'Legal Positivism', 'Critical Legal Studies', 'Law & Economics'],
    'Property Law': ['Real Property', 'Intellectual Property', 'Property Theory', 'Trusts & Estates'],
    'Human Rights Law': ['International Human Rights', 'Humanitarian Law', 'Refugee Law', 'Economic & Social Rights'],
  },
  'Medicine & Health Sciences': {
    'Anatomy & Physiology': ['Gross Anatomy', 'Neuroanatomy', 'Cardiovascular Physiology', 'Respiratory Physiology'],
    'Pathology': ['General Pathology', 'Systemic Pathology', 'Molecular Pathology', 'Forensic Pathology'],
    'Pharmacology': ['Pharmacokinetics', 'Pharmacodynamics', 'Clinical Pharmacology', 'Drug Discovery'],
    'Epidemiology': ['Disease Epidemiology', 'Clinical Epidemiology', 'Genetic Epidemiology', 'Environmental Epidemiology'],
    'Public Health': ['Global Health', 'Health Policy', 'Social Determinants of Health', 'Health Promotion'],
    'Medical Ethics': ['Bioethics', 'Clinical Ethics', 'Research Ethics', 'End-of-Life Ethics'],
    'Psychiatry': ['Mood Disorders', 'Psychotic Disorders', 'Anxiety Disorders', 'Neurodevelopmental Disorders'],
    'Oncology': ['Cancer Biology', 'Cancer Therapy', 'Immunotherapy', 'Cancer Epidemiology'],
    'Infectious Disease': ['Bacteriology', 'Virology', 'Parasitology', 'Antimicrobial Resistance'],
  },
  'Earth & Environmental Science': {
    'Geology': ['Mineralogy', 'Petrology', 'Structural Geology', 'Geomorphology', 'Stratigraphy'],
    'Climatology': ['Climate Dynamics', 'Climate Change', 'Paleoclimatology', 'Regional Climatology'],
    'Oceanography': ['Physical Oceanography', 'Chemical Oceanography', 'Marine Biology', 'Deep-Sea Science'],
    'Atmospheric Science': ['Atmospheric Dynamics', 'Atmospheric Chemistry', 'Meteorology', 'Aeronomy'],
    'Environmental Science': ['Pollution & Remediation', 'Conservation Science', 'Sustainability Science', 'Environmental Policy'],
    'Ecology': ['Population Ecology', 'Community Ecology', 'Ecosystem Ecology', 'Global Ecology'],
    'Geophysics': ['Seismology', 'Geomagnetism', 'Geodesy', 'Volcanology'],
    'Paleontology': ['Vertebrate Paleontology', 'Invertebrate Paleontology', 'Paleoecology', 'Astrobiology'],
  },
  'Engineering': {
    'Electrical Engineering': ['Circuits & Electronics', 'Signal Processing', 'Power Systems', 'Electromagnetics', 'Semiconductor Devices'],
    'Mechanical Engineering': ['Solid Mechanics', 'Thermodynamics & Heat Transfer', 'Fluid Mechanics', 'Manufacturing', 'Robotics & Mechatronics'],
    'Civil Engineering': ['Structural Engineering', 'Geotechnical Engineering', 'Transportation Engineering', 'Hydraulics', 'Environmental Engineering'],
    'Chemical Engineering': ['Transport Phenomena', 'Reaction Engineering', 'Separation Processes', 'Process Control'],
    'Biomedical Engineering': ['Biomechanics', 'Biomedical Imaging', 'Tissue Engineering', 'Neural Engineering'],
    'Materials Science': ['Metals & Alloys', 'Polymers', 'Ceramics', 'Nanomaterials', 'Electronic Materials'],
    'Aerospace Engineering': ['Aerodynamics', 'Propulsion', 'Spacecraft Design', 'Orbital Mechanics'],
    'Control Systems': ['Classical Control', 'Modern Control Theory', 'Optimal Control', 'Robust Control'],
  },
};

// Flat list of top-level fields (for sidebar ordering)
export const getSubfields = (field) => Object.keys(ACADEMIC_TAXONOMY[field] || {});
export const getSubSubfields = (field, subfield) => ACADEMIC_TAXONOMY[field]?.[subfield] || [];

